blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("posts.urls")),
]

blog/posts/urls.py
from django.urls import path
from . import views

app_name = "posts"
urlpatterns = [
    path("", views.posts_list, name="list"),
    path("<int:post_id>/", views.post_details, name="details"),
]

blog/main/models.py
from django.db import models

# Create your models here.

blog/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

blog/main/views.py
from django.shortcuts import render

# Create your views here.

blog/posts/views.py
from django.shortcuts import render
from .models import Post
# Create your views here.

def posts_list(request):
    posts = Post.objects.all()
    return render(request, "posts/list.ptml", {"posts": posts})

def post_details(request):
    posts = Post.objects.get(ig=post_id)
    return render(request, "posts/list.ptml", {"posts": posts})

blog/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta> name="viewport" content="width=device-width, initial-scale=0.1"
    <title>Blog</title>
</head>
<body>
    <nav>
      <a href="{% url 'posts:list' %}">Home</a>
    </nav>

  {% block content %}
  {% endblock %}

</body>
</html>

blog/posts/templates/posts/details.html
{% extends "posts/base.html" %}

{% block content %}
<h1>{{ post.title }}</h1>
<p>{{ post.content }}</p>
{% endblock %}

blog/posts/templates/posts/list.html
{% extends "posts/base.html" %}

{% block content %}
<h1>Posts</h1>
<ul>
{% for post in posts %}
  <li><a href="{% url 'posts:details' post.id %}">{{ post.title }}</a></li>
{% endfor %}
</ul>
{% endblock %}